    wildfly_download_url: http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.zip
    wildfly_base_filename: wildfly-10.0.0.Final
    wildfly_standalone_start_cmd: "nohup {{wildfly_home}}/{{wildfly_base_filename}}/bin/standalone.sh &> {{wildfly_home}}/nohup.out&"
    wildfly_deploy_path: "{{wildfly_home}}/{{wildfly_base_filename}}/standalone/deployments"
    legacy_app_url: "{{plusone_home}}/plusonelegacy/bin/plusone-legacy-application.war"
#  legacy_app_url: https://github.com/rduncan506/plusone/raw/master/plusonelegacy/bin/plusone-legacy-application.war
    legacy_app_deployment: plusone-legacy-application.war
    legacy_app_war: plusone-legacy-application.war


    oc_archive_name: openshift-origin-client-tools-v1.3.1-dad658de7465ba8a234a4fb40b5b446a45a4cee1-linux-64bit
    oc_home: "{{oc_install}}/{{oc_archive_name}}"
    oc_download_url: "https://github.com/openshift/origin/releases/download/v1.3.1/{{oc_archive_name}}.tar.gz"
    oc_command: "{{oc_home}}/oc"
    ocp_version: v3.3.0.32
    ocp_data_dir: "{{oc_install}}/data"
    ocp_username: "developer"
    ocp_password: "developer"
    openshift: "{{ansible_default_ipv4.address}}:8443"
    project_name: helloworld-msa
    msa_home: "{{plusone_home}}/plusonemsa"
    domain: "{{ansible_default_ipv4.address}}.xip.io"
    
    # Project definition - You don't need to change anything here
    msa_projects:
      - name: hola
        project: java
      - name: bonjour
        project: node
      - name: ola
        project: java

