---
# This playbook deploys a simple standalone JBoss server. 

- hosts: ocp-servers  
  remote_user: rduncan 
  become: no
  vars_files:
    - group_vars/user-vars.yml
    - group_vars/runtime-vars.yml

  roles:
    - install-msa
 
