---
# This playbook deploys a simple standalone JBoss server. 

- hosts: legacy-servers  
  remote_user: rduncan 
  become: no

  vars_files:
    - group_vars/user-vars.yml
    - group_vars/runtime-vars.yml
    
  roles:
    - wildfly-standalone
 

