---
# This playbook deploys a simple standalone JBoss server. 

- hosts: legacy-servers  
  remote_user: rduncan 
  become: no
  environment:
    JBOSS_PIDFILE: "wildfly.pid"
#https://github.com/openshift/origin/releases/download/v1.3.1/openshift-origin-client-tools-v1.3.1-dad658de7465ba8a234a4fb40b5b446a45a4cee1-linux-64bit.tar.gz
  vars:
    tmp_dir: /tmp
    oc_archive_name: openshift-origin-client-tools-v1.3.1-dad658de7465ba8a234a4fb40b5b446a45a4cee1-linux-64bit
    oc_install: /opt/testopenshift
    oc_home: "{{oc_install}}/{{oc_archive_name}}"
    oc_download_url: "https://github.com/openshift/origin/releases/download/v1.3.1/{{oc_archive_name}}.tar.gz"
#    oc_download_url: "https://github.com/openshift/origin/releases/download/v1.2.2/{{oc_archive_name}}.tar.gz"
    oc_command: "{{oc_home}}/oc"
    ocp_data_dir: "{{oc_install}}/data"
    ocp_username: "developer"
    ocp_password: "developer"
    openshift: 192.168.223.43:8443
    project_name: helloworld-msa
    msa_home: "/home/rduncan/redhat/projects/plusonenew/plusone/plusonemsa"
    domain: "192.168.223.43.xip.io"
    
    # Project definition - You don't need to change anything here
    msa_projects:
      - name: hola
        project: java
      - name: bonjour
        project: node
      - name: ola
        project: java

  roles:
    - install-msa
 

