---

- name: Check if wildfly already exists - {{wildfly_home}}/{{wildfly_base_filename}}
  stat: path="{{wildfly_home}}/{{wildfly_base_filename}}"
  register: p
- debug: msg="Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Download and extract wildfly archive - {{wildfly_download_url}}
  unarchive: 
    src={{wildfly_download_url}}
    dest={{wildfly_home}}
    remote_src=yes
  when: not p.stat.exists
                          
- name: Start WildFly - {{wildfly_standalone_start_cmd}}
  shell: '{{wildfly_standalone_start_cmd}}'

- name: Download Legacy binary
  get_url:
    url: '{{legacy_app_url}}'
    dest: '{{tmp_dir}}'

- name: Deploy the legacy application - url-{{tmp_dir}}/{{legacy_app_war}}, deployment-{{legacy_app_deployment}}, deploy_path-{{wildfly_deploy_path}}, src={{legacy_app_url}}
  jboss:  src={{tmp_dir}}/{{legacy_app_war}}
          deployment={{legacy_app_deployment}} 
          deploy_path={{wildfly_deploy_path}} 
          state=present
          
- file: path={{tmp_dir}}/{{legacy_app_war}} state=absent
