---

- name: Check if wildfly already exists - {{wildfly_home}}/{{wildfly_base_filename}}
  stat: path="{{wildfly_home}}/{{wildfly_base_filename}}"
  register: p
- debug: msg="Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Download and extract wildfly archive - {{wildfly_download_url}}
  unarchive: 
    src={{wildfly_download_url}}
    dest={{wildfly_home}}
    remote_src=yes
  when: not p.stat.exists
                          
- name: Start WildFly - {{wildfly_standalone_start_cmd}}
  shell: '{{wildfly_standalone_start_cmd}}'

- name: Deploy the legacy application
  jboss:  src={{legacy_app_url}}
          deployment={{legacy_app_deployment}} 
          deploy_path={{wildfly_deploy_path}} 
          state=present
 
- copy:
    src: "{{plusone_home}}/plusonelegacy/src/main/webapp/services.json"
    dest: "{{wildfly_home}}/{{wildfly_base_filename}}/welcome-content"
    mode: 0644
